updating annotation
Signed-off-by: vsoch <vsochat@stanford.edu>

diff --git a/.github/workflows/issue-annotation.yml b/.github/workflows/issue-annotation.yml
--- a/.github/workflows/issue-annotation.yml
+++ b/.github/workflows/issue-annotation.yml
@@ -22,13 +22,15 @@ jobs:
       env:
         GITHUB_LABEL: ${{ github.event.issue.labels[0].name }}
       run: |
+          if [[ "${GITHUB_LABEL}" != "taxonomy" ]] || [[ "${GITHUB_LABEL}" != "criteria" ]]; then 
+              printf "A label of taxonomy or criteria is required.;
+              exit 1;
+          fi
+
           echo "${{ github.event.issue.body }}" > new-issue.txt
           # rse annotate (criteria|taxonomy) --file (filename) --username (user)
           echo "rse annotate ${GITHUB_LABEL} --file new-issue.txt --username ${{ github.event.issue.user.login }}"
           rse annotate ${GITHUB_LABEL} --file new-issue.txt --username "${{ github.event.issue.user.login }}"
-
-
-# TODO this will need to update interface when annotate rendered there
 
     - name: Checkout New Branch
       env:
@@ -38,8 +40,19 @@ jobs:
         GITHUB_USER: "{{ github.event.issue.user.login }}"
       run: |
         printf "GitHub Actor: ${GITHUB_ACTOR}\n"
-        export BRANCH_FROM="annotate/${GITHUB_LABEL}-${GITHUB_USER}-$(date '+%Y-%m-%d')"
+        export BRANCH_FROM="annotate/${GITHUB_LABEL}-${GITHUB_USER}"
         git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
+
+        # Test if branch exists in remote
+        BRANCH_EXISTS=$(git ls-remote --heads origin ${BRANCH_FROM})
+        if [[ -z ${BRANCH_EXISTS} ]]; then
+            printf "Branch does not exist in remote.\n"
+        else
+            printf "Branch already exists in remote.\n"
+            echo 1
+        fi
+        echo "::set-env name=BRANCH_EXISTS::${BRANCH_EXISTS}"
+
         git branch
         git checkout -b "${BRANCH_FROM}" || git checkout "${BRANCH_FROM}"
         git branch
@@ -58,9 +71,19 @@ jobs:
            git push origin "${BRANCH_FROM}"
         fi
         echo "::set-env name=PULL_REQUEST_FROM_BRANCH::${BRANCH_FROM}"
-
+        
     - name: Open Pull Request
       uses: vsoch/pull-request-action@1.0.6
+      id: pr
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         PULL_REQUEST_BRANCH: "master"
+
+     - name: Comment Pull Request with Issue
+        if: steps.pr.outputs.pull_request_return_code == 0 && success()
+        env:
+          ISSUE_URL: https://github.com/${GITHUB_REPOSITORY}${{ steps.pr.outputs.pull_request_number }}
+        uses: marocchino/sticky-pull-request-comment@v1.1.0
+        with:
+          message: 'Relevant issue is at ${{ ISSUE_URL }}'
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
